# Generated by Django 3.2 on 2023-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytype',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
